template_type: K8S
template_version: 12.0


template_parameters:
variables:
  key1: 

tags:
- Org:Engineering
- Team:Shift_Left
- env1:securityAudit
- CircleCI:Engineering
- teama:apple
- teama1:apple1
- teama1:apple2
- teama2:apple3
- teama3:apple4
- teama4:apple5
