
template_type: TF
template_version: 0.11
template_parameters:
variables:
operatingsystem : "Hello\nconnected"
version: 1.0
compiler: "Terraform\t\tlatest" 

tags:
- Org:Engineering
- Team:Shift_Left
- PrismCloud:SecurityAudit
- env:SecurityAudit
