template_type: TF
template_version: 0.9 


template_parameters:
  variables:
    operatingsystem: Helloconnected
    version: 1
    compiler: Terraformlatest
  
tags:
- Org:Engineering
- Team:Shift_Left
- env1:securityAudit
- env26:z
- env21:jags
