template_type: CTF 
template_version: 0.9 


template_parameters:
  variables:
    operatingsystem: Helloconnected
    version: 1
    compiler: Terraformlatest
  variable_files:
  - ./cft_variable/CFT_variable_files/cft_variables.json
  
tags:
- Org:Engineering
- Team:Shift_Left
- env1:securityAudit
- env26:z
- env21:jags
