
template_type: TF

template_version: 12.0

template_parameters:
variables:
  key1 : value1
  key2 : value2
variable_files:
 - ./filepath/filename1
 - ./filepath/filename2

tags:
- Org:Engineering
- Team:Shift_Left
