
template_type: TF
template_version: 0.11
template_parameters:
variables:
- operatingsystem: Helloconnected
- version: 1
- compiler: Terraformlatest 

tags:
- Org:Engineering
- Team:Shift_Left
- PrismCloud:SecurityAudit
- env:SecurityAudit
