version: 2.1
orbs:
  pcs: pcs_sl_dev/devops_security@dev:first

jobs:
  docker_safe_build:
    executor: pcs/compute
    steps:
      - checkout
      - run: 'docker pull nginx'
      - pcs/scan_image:
          prisma_cloud_compute_url: https://staging-consoles.cloud.twistlock.com/aws-singapore-961095203
          prisma_cloud_compute_username: jmurugesan@paloaltonetworks.com 
          prisma_cloud_scan_image: nginx
          reports: csv,junit
workflows:
  scan:
    jobs:
      - pcs/scan_iac:
          prisma_cloud_api_url: https://apik8stage.k8s.prismacloud.io
          templates_directory_path: ./
          prisma_cloud_failure_criteria: High:1,Medium:2,Low:6
          prisma_cloud_tags: "env26:a"
          prisma_cloud_asset_name: "CircleCI-SCANAPI"
          reports: csv,junit
      - docker_safe_build
