version: 2.1
template_type: TF
template_version: 0.9 

template_012_parameters:
 - root_module: ./tfplan/terraform12module/
  variable_files:
    - ./tfplan/terraform12module/smelks.tfvars
  
template_parameters:
  variables:
    operatingsystem: Helloconnected
    version: 1
    compiler: Terraformlatest
    scanPlanFilesOnly: True
  
tags:
- Org:Engineering
- Team:Shift_Left
- env1:securityAudit
- env26:z
- env21:jags
