version: 2.1
orbs:
  pcs: pcs_sl_dev/devops_security@dev:first

jobs:
  docker_safe_build:
    executor: pcs/compute
    steps:
      - checkout
      - run: 'docker pull nginx'
      - pcs/scan_image:
          prisma_cloud_compute_url: https://us-east1.cloud.twistlock.com/app0panwdev-1234
          image: nginx 
          reports: none 
workflows:
  scan:
    jobs:
      - pcs/scan_iac:
          prisma_cloud_api_url: https://apik8stage.k8s.prismacloud.io
          templates_directory_path: ./tf11
          prisma_cloud_failure_criteria: High:1000,Medium:19,Low:2,Operator:or
          prisma_cloud_tags: "env1:A,env2:B,env3:C,env4:D,env5:E,env6:F,env7:G,env8:H,env9:I,env10:J,env11:K,env12:L,env13:M,env14:N,env15:O,env16:P,env17:Q,env18:R,env19:S,env20:T,env21:U,env22:V,env23:W,env24:X,env25:Y,env26:Z,Orgn:PANW"
          reports: csv,junit

      
