version: 2.1
orbs:
  pcs: pcs_sl_dev/devops_security@dev:first

jobs:
  docker_safe_build:
    executor: pcs/compute
    steps:
      - checkout
      - run: 'docker pull elasticsearch'
      - pcs/scan_image:
          prisma_cloud_compute_url: https://us-east1.cloud.twistlock.com/app0panwdev-1234
          prisma_cloud_scan_image: elasticsearch 
          reports: csv,junit
workflows:
  scan:
    jobs:
      - pcs/scan_iac:
          prisma_cloud_api_url: https://apik8stage.k8s.prismacloud.io
          templates_directory_path: ./k8s/
          prisma_cloud_failure_criteria: High:1,Medium:2,Low:6
          prisma_cloud_tags: "env26:z"
          reports: csv,junit
