version: 2.1
orbs:
  prisma: prisma_cloud/devops_security@2.2.0
workflows:
  scan:
    jobs:
      - prisma/iac_scan:
          prisma_cloud_api_url: https://api2slqa.k8sdev.prismacloud.io/
          templates_directory_path: ./tf12_with_issues
          access_key: PC_ACCESS_KEY
          secret_key: PC_SECRET_KEY
          failure_criteria_high_severity: 1
          failure_criteria_medium_severity: 2
          failure_criteria_low_severity: 3
          failure_criteria_operator: and
          tags: 'env:development, team:devOps'
      - docker_safe_build
